view = "timeseries-classification"
metadata = "/Users/acabrera/dev/data/motionsense/motionsense.csv"
data_path = "/Users/acabrera/dev/data/motionsense/A_DeviceMotion_data/A_DeviceMotion_data"
data_column = "file"
id_column = "file"
label_column = "label"
batch_size = 16
samples = 15
port = 8004