functions = "./"
view = "image-classification"
metadata = "../examples/cifar/cifar_pred.csv"
data_path = "../data/CIFAR-10-images/test"
data_column = "id"
label_column = "label"
models = [] # Add paths to model checkpoints, passed into @model
